### ISSUE TITLE
Launch mathesar.org website

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#4]
### Foundational work
- [x] Scaffolding
  - [x] Create repo
  - [x] Set up Jekyll
  - [x] Set up GitHub Pages
  - [x] Put current draft of content into Jekyll
- [x] Finalize design in Figma
- [x] Implement design in Jekyll

```[tasklist]
### Blocks usability testing
- [x] #12
- [x] #6
- [x] #8
- [x] #18 
- [x] #25
- [x] #29 
- [x] #7
- [x] #35
- [x] #37
- [x] #11
- [x] #22 
```

```[tasklist]
### Blocks launch
- [x] #24
- [x] #30
- [x] #13
- [x] #9
- [x] #10
- [x] #33
- [x] #23
- [x] #44
- [x] https://github.com/centerofci/mathesar-website/issues/45
```
