### ISSUE TITLE
Copy updates - first pass

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#7]
### Homepage
- [x] Hero list ("Built on Postgres", etc.)
- [x] Finalize use cases
- [x] Copy for use cases
- [x] Rethink action items

### About Us
- [x] Rewrite "About Mathesar" section
- [x] Rewrite "Our Mission" section 
- [x] Write team achievements section
- [x] Write team bios
- [x] Rewrite sustainability section

### How it Works - Dev
- [x] Finalize "you can also use Mathesar for" use cases
- [x] Review Section 3 text and make tweaks as needed
- [x] Review special use cases header and text
- [x] Rethink action items

### How it Works - Non-dev
- [x] Review Ghislaine quote
- [x] Review Section 4 text and make tweaks as needed
- [x] Rethink action items

### FAQ
- [x] Rewrite forms FAQ
- [x] Rewrite access control FAQ
- [x] Rewrite formulas FAQ
- [x] ~Rewrite sustainability FAQ~ removed entirely

### Roadmap
- [x] Rewrite intro text
- [x] Populate roadmap

### Request installation
- [x] Rewrite intro
- [x] Rewrite services section
- [x] Rewrite form
- [x] Rewrite next steps section

### General
- [x] Update mailing list copy
- [x] Improve page titles

### Community
*We're removing this page.*

- [x] ~Review welcome text~
- [x] ~Review users text~
- [x] ~Review developers text~

### FAQ
- [x] Rewrite spreadsheet FAQ
- [x] Rewrite Airtable FAQ
- [x] Rewrite Baserow FAQ
- [x] Rewrite NocoDB FAQ

### Roadmap
- [x] Revise roadmap based on feedback

### Fix results of bad merge 
- [x] Double check action items
- [x] Double check community links

### Footer
- [x] Update year in footer
