### ISSUE TITLE
Mathesar launch publicity checklist

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#78]
*This isn't exactly related to the website, but I wanted to track publicity related tasks with the rest of my tasks, so I made this.*

### Announcements
- [x] [Hacker News](https://news.ycombinator.com/), [posted](https://news.ycombinator.com/item?id=34999774) 2023-03-02
- [x] CCI Twitter, [tweeted](https://twitter.com/centerofci/status/1631383963053826048) 2023-03-02
- [x] Mathesar Twitter. [tweeted](https://twitter.com/mathesar_org/status/1631384636096913421) 2023-03-02
- [x] LinkedIn, [posted](https://www.linkedin.com/posts/centerofci_mathesar-activity-7037435303845908480-VvKt/) 2023-03-03
- [x] CCI blog, [posted](https://centerofci.org/introducing-mathesar-an-open-source-database-interface-for-everyone/) 2023-03-02
- [x] [/r/opensource/](https://www.reddit.com/r/opensource/) - @kgodey  - [posted](https://www.reddit.com/r/opensource/comments/11kdb5e/we_just_released_mathesar_an_intuitive_ui_for/) 2023-03-06
- [x] [Svelte Discord server](https://discord.com/invite/svelte) - @seancolsen
- [x] [/r/selfhosted/](https://www.reddit.com/r/selfhosted/) - @kgodey [posted](https://www.reddit.com/r/selfhosted/comments/11n2fxx/mathesar_intuitive_ui_for_managing_data_for_users/) 2023-03-09
- [ ] [/r/PostgreSQL/](https://www.reddit.com/r/PostgreSQL/) - @kgodey 
- [ ] [/r/Database/](https://www.reddit.com/r/Database/) - @kgodey 
- [ ] [/r/sveltejs/](https://www.reddit.com/r/sveltejs/) - @pavish 
- [ ] CCI Slack
- [ ] https://www.reddit.com/r/Python/?f=flair_name%3A%22Intermediate%20Showcase%22
- [ ] https://www.reddit.com/r/programming/
- [ ]  https://www.reddit.com/r/django/?f=flair_name%3A%22Apps%22
- [ ] https://www.reddit.com/r/coolgithubprojects/

### Emails
- [x] CCI board
- [ ] Mathesar announcements mailing list
- [ ] Mathesar developers mailing list
- [ ] GitHub stargazers?
- [ ] "Influencers"
  - [ ] Create draft
  - [ ] Create list of people
  - [ ] Send to list
  - [ ] Share with rest of team
- [ ] Personal networks
  - [ ] Create draft
  - [ ] Create list of people
  - [ ] Send to list
  - [ ] Share with rest of team
- [ ] Content creators  
  - [ ] Create draft
  - [ ] Create list of creators
  - [ ] Send to list
- [ ] Set up mailing list automated welcome email

## Resources
- Drafts are being written in [this private document](https://docs.google.com/document/d/1s8WL0Uc9ak4jjHpOP6Mg0r2xsYN-SjbW5pcthF8ejLY/)
- Show HN [Rules](https://news.ycombinator.com/showhn.html) & [Tips](https://news.ycombinator.com/item?id=22336638)
- See also: #84

**Comment by silentninja** [comment]
Additional Subreddits to consider
- https://www.reddit.com/r/Python/?f=flair_name%3A%22Intermediate%20Showcase%22
- https://www.reddit.com/r/programming/
- https://www.reddit.com/r/django/?f=flair_name%3A%22Apps%22
- https://www.reddit.com/r/coolgithubprojects/

**Comment by silentninja** [comment]
We should also add Mathesar to the https://ossdatabase.com/

**Comment by kgodey** [comment]
Thanks @silentninja. With subreddits, we need to make sure they're at least somewhat open to people promoting their own projects, or that we can make a compelling enough post for the audience of the subreddit without being promotional. I'll investigate these next week and add them to the main list if they meet the criteria.

**Comment by seancolsen** [comment]
Closing because this does not seem relevant anymore
