### ISSUE TITLE
Finalize website design - first pass

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#8]
### Homepage
- [x] Hero
   - [x] Ensure action buttons are above the fold
   - [x] Align text and image properly
   - [x] Consider emphasizing "open source" somehow
- [x] Section 1
  - [x] Remove `<br/>` tags but make sure text doesn't get any wider
  - [x] There should be more distinctiveness between bold and normal font
  - [x] Finalize text sizes
- [x] Section 2
  - [x] Finalize text sizes
- [x] Section 3: Use Cases
  - [x] Finalize layout
- [x] Section 4
  - [x] Text should be narrower
- [x] Mailing list signup
  - [x] Fix width of email input

### About Us
- [x] Finalize text sizes and width for all sections
- [x] Team section
  - [x] Ensure that the bios can support line breaks
  - [x] Ensure that bios layout supports longer text
  - [x] Style the "achievements" section better
  - [x] Add correct team photos
  - [x] Add open source contributors (Github)
- [x] Add community contributors to this page
- [x] Sustainability section
  - [x] Add logos of funders

### How it Works - Dev
- [x] Finalize text sizes and width for all sections
- [x] Hero - see homepage feedback
- [x] Section 1 (quote)
	- [x] move attribution to the bottom
	- [x] Fix Pavish's photo cropping on narrow screens
- [x] Section 2
	- [x] Text is too wide
	- [x] Remove horizontal line – it creates a barrier where the text is narrative
- [x] Section 3
	- [x] Text needs some emphasized parts
	- [x] Text is too narrow on narrow screens, we should stack images and text
- [x] Section 4
	- [x] Improve styling – text sizes and emphasis looks off
- [x] Section 5
	- [x] Text is too narrow on narrow screens, cards should stack sooner
	- [x] Some parts of the text needs emphasis
	- [x] "You can also use Mathesar for" section should be styled better
- [x] Section 6
	- [x] Improve styling – text sizes and emphasis looks off

### How it Works - Non-dev
- [x] Finalize text sizes and width for all sections
- [x] Hero - see homepage feedback
- [x] Section 1
	- [x] Improve styling – text sizes and emphasis looks off
- [x] Section 2 - see Section 1 feedback on "dev" page
- [x] Section 3
	- [x] Improve styling – text sizes and emphasis looks off
- [x] Section 4 - same feedback as Section 3 in "dev" page

### FAQ
- [x] Page title needs better styling, whitespace looks awkward on larger screens
- [x] Order shoud be Features, About Mathesar, Product Comparisons 
- [x] Creating and sharing forms should be part of features
- [x] ToC – section titles should be red

### Community
- [x] Finalize text sizes and width for all sections
- [x] Swap positions of Mathesar users & Mathesar developers section
- [x] Improve text sizes and emphasis

### Roadmap
- [x] Remove "Coming soon"  header section
- [x] Improve text width and styling on introductory section
- [x] Roadmap cards 
	- [x] There should be at least 2-3 cards per row
	- [x] Cards should only have title and link to discussion (remove subtitle and description)
	- [x] Cards should belong to a category (similar to FAQs)
- [x] Feedback section – remove line and "feedback" title.
- [x] Feedback section – link color doesn't have enough contrast.

### Request installation
- [x] Finalize text sizes and width for all sections
- [x] Form
	- [x] Replace first and last name with "Full name"
	- [x] Make full name and email inputs less wide
	- [x] Button should not be as wide as the inputs
- [x] "Next" section should be more prominent

### Responsiveness
- [x] Ensure all pages work on very wide screen
- [x] Ensure all pages work on narrow screens
- [x] Ensure that the site looks good close to responsive breakpoints

### Footer
- [x] Link to GitHub & Twitter
- [x] Link to License
- [x] Link to CCI website
